In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

pred_df = pd.read_csv('desktop/independant_projects/movie_score_predictor/ML_dataset1.csv')

pred_df.head()

year  duration  month_published  US_involvement  india_involvement  \
0  1894        45               10               1                  0   
1  1906        70               12               0                  0   
2  1911        53                8               0                  0   
3  1912       100               11               1                  0   
4  1911        68                3               0                  0   

   japan_involvement  china_involvement  Canada_involvement  \
0                  0                  0                   0   
1                  0                  0                   0   
2                  0                  0                   0   
3                  0                  0                   0   
4                  0                  0                   0   

   France_involvement  English_presence  ...  Horror  Music  Musical  Mystery  \
0                   0                 0  ...       0      0        0        0   
1                   0                 0  ...       0      0        0        0   
2                   0                 0  ...       0      0        0        0   
3                   0                 1  ...       0      0        0        0   
4                   0                 0  ...       0      0        0        0   

   Romance  Sci-Fi  Sport  Thriller  War  Western  
0        1       0      0         0    0        0  
1        0       0      0         0    0        0  
2        0       0      0         0    0        0  
3        0       0      0         0    0        0  
4        0       0      0         0    0        0  

[5 rows x 39 columns]

In [5]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler



In [6]:
#split out the y column and drop the x column 
#split the data into training and testing sets
#scale the features so that date doesn't play an outsized role

Y = pred_df[['is_liked']].copy()

Y = np.ravel(Y)

X = pred_df.drop(columns = ['is_liked'])

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state = 42)

X_s = MinMaxScaler().fit(X_train)

X_tr_scale = X_s.transform(X_train)
X_ts_scale = X_s.transform(X_test)


In [7]:
X_tr_scale

array([[0.81746032, 0.08474576, 0.18181818, ..., 0.        , 0.        ,
        0.        ],
       [0.78571429, 0.04563233, 1.        , ..., 0.        , 0.        ,
        0.        ],
       [0.61111111, 0.06388527, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.96825397, 0.08996089, 0.72727273, ..., 0.        , 0.        ,
        0.        ],
       [0.28571429, 0.07692308, 0.63636364, ..., 0.        , 0.        ,
        0.        ],
       [0.61904762, 0.06127771, 0.27272727, ..., 0.        , 0.        ,
        0.        ]])

In [8]:
X_ts_scale

array([[0.97619048, 0.0821382 , 0.27272727, ..., 0.        , 0.        ,
        0.        ],
       [0.92063492, 0.06127771, 0.63636364, ..., 0.        , 0.        ,
        0.        ],
       [0.79365079, 0.07692308, 0.27272727, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.26984127, 0.14341591, 0.90909091, ..., 0.        , 0.        ,
        0.        ],
       [0.8968254 , 0.05736636, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.94444444, 0.09387223, 0.63636364, ..., 0.        , 0.        ,
        0.        ]])

In [9]:
Y_train

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [11]:
#try a support vector machine model
from sklearn.svm import SVC
from sklearn.metrics import classification_report

movie_preds_svc = SVC(kernel='linear')

movie_preds_svc.fit(X_tr_scale, Y_train)



SVC(kernel='linear')

In [12]:
mov_preds_svc = movie_preds_svc.predict(X_ts_scale)

mov_preds_svc

array([1, 0, 0, ..., 1, 0, 1], dtype=int64)

In [14]:
print(classification_report(Y_test, mov_preds_svc))

              precision    recall  f1-score   support

           0       0.69      0.64      0.66     10174
           1       0.69      0.74      0.71     11290

    accuracy                           0.69     21464
   macro avg       0.69      0.69      0.69     21464
weighted avg       0.69      0.69      0.69     21464

